// All string actions here.

export const FETCH_SORTING_PLACES = 'FETCH_SORTING_PLACES';
export const FETCH_SORTING_PLACE_INFO = 'FETCH_SORTING_PLACE_INFO';
export const UPDATE_CURRENT_PLACE = 'UPDATE_CURRENT_PLACE';
export const UPDATE_SELECTED_CATEGORIES = 'UPDATE_SELECTED_CATEGORIES';

export const VOTE_UP_SORTING_PLACE = 'VOTE_UP_SORTING_PLACE';
export const VOTE_DOWN_SORTING_PLACE = 'VOTE_DOWN_SORTING_PLACE';

export const SAVE_USER_LOCATION = 'SAVE_USER_LOCATION';

export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';