// All string actions here.

export const FETCH_SORTING_PLACES = 'FETCH_SORTING_PLACES';
export const FETCH_SORTING_PLACE_INFO = 'FETCH_SORTING_PLACE_INFO';
export const UPDATE_CURRENT_PLACE = 'UPDATE_CURRENT_PLACE';

export const VOTE_UP_SORTING_PLACE = 'VOTE_UP_SORTING_PLACE';
export const VOTE_DOWN_SORTING_PLACE = 'VOTE_DOWN_SORTING_PLACE';

export const SAVE_USER_LOCATION = 'SAVE_USER_LOCATION';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const MODIFY_RANGE = 'MODIFY_RANGE';