// All string actions here.

export const UPDATE_SORTING_PLACES = 'UPDATE_SORTING_PLACES';
export const ADD_SORTING_PLACE_INFO = 'ADD_SORTING_PLACE_INFO';
export const UPDATE_CURRENT_PLACE = 'UPDATE_CURRENT_PLACE';

export const VOTE_UP_SORTING_PLACE = 'VOTE_UP_SORTING_PLACE';
export const VOTE_DOWN_SORTING_PLACE = 'VOTE_DOWN_SORTING_PLACE';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';

export const SAVE_USER_LOCATION = 'SAVE_USER_LOCATION';

export const FETCHING_PLACES = 'FETCHING_PLACES';
export const FETCHING_INFO = 'FETCHING_INFO';
export const STOP_FETCHING_INFO = 'STOP_FETCHING_INFO';
export const STOP_FETCHING_PLACES = 'STOP_FETCHING_PLACES';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';